server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10


# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # SC 渠道配置 - 拼团对接渠道值、回调通知
    group-buy-market:
      api-url: http://127.0.0.1:8091
      notify-url: http://127.0.0.1:8080/api/v1/test/group_buy_notify
      source: s01
      chanel: c01


# 微信公众号对接
weixin:
  config:
    originalid: gh_84007f212185
    token: b8b6
    app-id: wx8fa84c9c3d361d7f
    app-secret: cd0f69db3147b307fb068f93793b3c5d
    template_id: rDKpV4F4nTqb_2KAy4DydAfqMJt8Cmfj-pKekfrBiOQ

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000149696197
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRpJSjOPPaz2Eo7ZahHg3Sg0Est/zLRc+J3GxbMxWFLOSeOsAx+TywauwTecobg3ProkAnYQAfgw30La3VjmJOxmiZ74ztTyL4o/wPw2gih0bXGpiymrc7ebtSXRgqMKle2VTb7b0rx8DjpaFl+f0L9LnU0MLL8ZmU7xuktMOEcQLtvwFlpwn3VcMcxeDd6cMZVfjPOcNCC0awNfE3kDbyHsb53qL/YKr0d/tcHnpb18avAJLdiMeJJWD38MCZQE1CNhKetv+bANjyaE6Y6IFwudeA4eKG5ef2j5VCWYv8l4+xJ1f/c+xW43gz1Vb3E/Yblu17AhD9bYstA1TahKw1AgMBAAECggEAFuBZEIJDm1zzj/AxtsD3vtcrB5Emve8LOEZNJs4RVUfF6SylP7Q8WiGRT0XT/xpYvOxRU14jHNADAxWhtmeU/Xagu30rD6NchN2NHBS/aJ0C/YqJ7ZPrsAXg7ID+6LGYCPPuJlVjX1sS6y76+P+ZRaV9AvZ/gnVCgGhGWUqjY0v4NU64HP8iV28sZBpO2GgKZX5bCQY7uhTAgrx+drpIuVJaW17pvyuQAjg6Oo85bZT3DvGBnIBmZjQotE7KVz7NwSN/2/YJ82GLeBLaORMdP0a35DQ5L4NEa8Mcamt45E4ECT1MeASlU/RpD4OWP7DT24TYi1+zUF4i7PQrWDi4SQKBgQDOOu7Z0QQLKBMjyXuNgB4ywbYmLwxWky0vfCXB3BwIfTY7CP/LeFElgkpDwfT3sGUqOOIV7hhDSB6i+89bVzUQY0Izrq6chWwjcqbocuWivxenewwfVbSII0Zef7amuB4GmTqdkg+C+xLB+hq6zkiWxrFupBsyrcu5amYDtVxH+wKBgQC0yoPSVlWFPIvKd0h2NvpMHR0yyLtbd0xxo6ZQNBe7koZ4zHsKTsZT6aSHiTcW0Xy94y4KyX1G3Nc4U/rVKrz5ufdgngSPN1DLvcU4sKWNz4baQIXMph1uX3VgZwWxGSFxCfcH/ELOHMEeYM6Cz6M+y2dopqZw4utMr0n/tvy1jwKBgFg6slERsQ8s1/NpkahZ9ZF1en4fhsHLOXulO2oSxxOCrh7XnMfp851+flM6uZj2KHHF4EPNlyfBxQmpfW7wgk0+ieYeh6mDE16fAHVWIpRb+Ly4UdleC1xq6wIm1XfCMWZVS9R51pUM4VuHqsPc2QVYgDR7lP87h3sN4BMaFh7dAoGAKGcRqpHsrsfnHaomoXSL3zKqccz2QeyZQtQluMrLevm1340i+hy8qcgPItMBYrISRIVepr58prd3yXjLF5RjgxOSOx9VOYRNJBsW1iJz/QshweilfiSpcx8WJiMf3IIXPSHS+Q/hBhra9aUAwa8RdlkSlQqZK6UqnIqX6PPF6fUCgYEApu0bVBot/V0ME8rcgKvYYEj/DU/MQehLjR0qgu8tgxvz5E7LfeKTixtRNJcEYTQz3+vlSrVN0ZUvfNS9SFMngq4QqQJ5KcXzBuPpDklCOLLWyyPvctnTUkllwAw6jT3r3RUzUTVAFB5IzcIikZK2EzDRLK8nlVVIcAf/+LEp6I0=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqG2MksYQS+wqgmLo1iXGMJW1cOVYEmuBM4rUOmk6q4irnqIpsMdtEewwUeXO7aW9Y99t7RGVJbuQ85bY8Fj3tCER2NYUtwgSDSZLNeyE8+l7NRuaEXu8pUziskakZD5y57C+n9oFhWjxpNuzgPS7XKLd7FAoqWHKy5bh9sUsDPmwsAZSgzxofYiowkc2AIukPxZ2p8EwCP2+Vd1bZzBjmFvojnvjbdjzL5ca4mTUfigFxaZcTRGaDaZxAcaX9UGChbS396zSaITWD0eGvhlD0FT8h32o5YVddM79W8VdeEg2z5vz2VVJCIqxBpirqaZn0qML86Z+s8+pEo4l8Q0XBwIDAQAB
  notify_url: https://api.zkyhwx.top/api/v1/alipay/alipay_notify_url
  return_url: https://front.zkyhwx.top
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml